name: Thomas Calvert
favicon: null
layout_spectrum: 0.00886
typography_spectrum: 0.5037558686453849
title: My personal test site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbcbcb'
    - '#23375c'
    - '#97a5b2'
    - '#3f5c86'
    - '#6d8ba3'
  brandStrength: 0.6810368082951754
  lightness: 0.11442165006883442
  saturation: 0.006896457867696881
  rhythmicContrast: 0.10878274496644735
purpose: []
